### ISSUE TITLE
Does not creates a push event

### ISSUE THREAD

**Issue by mildred** [endre-spotlab/fast-forward-js-action#36]
This action does not seem to create a GitHub push event, workflows registered on the target branch with a push event are not executed.

**Comment by oakkitten** [comment]
This is probably due to workflows not being allowed to start other workflows in order to avoid loops. You can get around the above limitation by using a GitHub app. Here are [some instructions](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens) to set one up.


In the end, since my use case was rather simple, and since I wasn't sure what `staging_branch` is supposed to be, I decided to do this by hand. The following works for me and runs all checks. `LOKSMITH_ID` and `LOCKSMITH_PRIVATE_KEY` are the id and private key of this repo-scoped GitHub app with repo write permissions. (I also needed the workflow permission since I'm modifying my workflow files as well.)

```yml
name: Fast-forward

on:
  issue_comment:
    types: [created, edited]

jobs:
  fast_forward:
    name: Fast-forward
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      github.event.comment.author_association == 'OWNER' && 
      contains(github.event.comment.body, '/fast-forward')

    steps:
      - name: Generate access token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.LOKSMITH_ID }}
          private_key: ${{ secrets.LOCKSMITH_PRIVATE_KEY }}

      - name: Fetch repository
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Checkout pull request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Fast-forward & push
        run: |
          export PR_COMMIT=$(git rev-parse HEAD)
          git checkout main
          git merge --ff-only $PR_COMMIT
          git push origin main
```

The same, but instead of reacting to a comment, this reacts to applying the label `fast-forward`:

```yaml
name: Fast-forward

on:
  pull_request:
    types: [labeled]

jobs:
  fast_forward:
    name: Fast-forward
    runs-on: ubuntu-latest
    if: github.event.label.name == 'fast-forward'

    steps:
      - name: Generate access token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.LOKSMITH_ID }}
          private_key: ${{ secrets.LOCKSMITH_PRIVATE_KEY }}

      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Fast-forward & push
        env:
          PR_COMMIT: ${{ github.event.pull_request.head.sha }}
        run: |
          git checkout main
          git merge --ff-only "$PR_COMMIT"
          git push origin main
```

**Comment by mhostetter** [comment]
@mildred did you ever find a solution?

Unfortunately not being able to initiate my `on: push` workflows might force me to continue using GitHub's normal rebase & merge. 😞

**Comment by andreiborisov** [comment]
The solution is quite simple: instead of using automatically provided `GITHUB_TOKEN` which doesn't trigger events, create a personal access token, put it in GitHub secrets and use it as such:

```yaml
- name: Fast-forward PR
  uses: endre-spotlab/fast-forward-js-action@2.1
  with:
    GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
```

Where `WORKFLOW_GITHUB_TOKEN` is the name of the secret you've created.

@endre-spotlab probably makes sense to put it in `README` and close the issue, since it's a purposeful limitation of automatically provided `GITHUB_TOKEN`: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow.
