### ISSUE TITLE
how do i actually use this?

### ISSUE THREAD

**Issue by simkimsia** [endre-spotlab/fast-forward-js-action#37]
i copied your existing workflow word for word

but nothing happened

```
on:
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      # Basic use case example
      - name: Fast Forward PR
        id: ff-action
        uses:  ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Cannot do fast forward!'
```

as `fast-forward.yml` then i type `/fast-forward` in a pull request as comment. nothing happened

**Comment by simkimsia** [comment]
Tried on a private repo. definitely does not work

What i use as `fast-forward.yml` this time
```
on:
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Fast Forward PR
        uses: endre-spotlab/fast-forward-js-action@2.1
```

![image](https://user-images.githubusercontent.com/245021/141750497-10c7d0c1-6262-4ea2-8662-5f04c5645f66.png)

**Comment by demisx** [comment]
Worked for me. 🤷🏻‍♂️   Here is my `fast-forward-pr.yml`:

```yaml
name: Fast-Forward PR

on: 
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')   
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Basic use case example
      - name: Fast Forward PR
        id: ff-action
        uses: endre-spotlab/fast-forward-js-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Cannot do fast forward!'
          staging_branch: 'main'
          production_branch: 'prod'
```
